HW1: ReservationSystem.o Flight.o Reservation.o
		g++ ReservationSystem.o Flight.o Reservation.o -o hw1
		
ReservationSystem.o: ReservationSystem.cpp ReservationSystem.h
	g++ -c ReservationSystem.cpp
	
Flight.o: Flight.cpp Flight.h
	g++ -c Flight.cpp

Reservation.o: Reservation.cpp Reservation.h
	g++ -c Reservation.cpp